In [1]:
import numpy as np

def load_frametimes(base_path, num_cameras=6):
    """
    Load frametimes.npy files for a specified number of cameras.

    Parameters:
    - base_path (str): The base path where the main folder is located.
    - num_cameras (int): The number of cameras to load frametimes for. Default is 6.

    Returns:
    - dict: A dictionary with camera names as keys and frametimes data as values.
    """
    frametimes = {}
    for i in range(1, num_cameras + 1):
        camera_path = f'{base_path}/videos/Camera{i}/frametimes.npy'
        try:
            frametimes[f'Camera{i}'] = np.load(camera_path)
            print(f"Loaded frametimes for Camera{i}")
        except FileNotFoundError:
            print(f"File not found: {camera_path}")
    return frametimes

# Example usage
base_path = '/hpc/group/tdunn/Bryan_Rigs/BigOpenField/24summ/2024_08_29/20240717_PMCr2'
# base_path = '/hpc/group/tdunn/Bryan_Rigs/BigOpenField/24summ/2024_10_04/20240916V1r2/'
frametimes_data = load_frametimes(base_path)


Loaded frametimes for Camera1
Loaded frametimes for Camera2
Loaded frametimes for Camera3
Loaded frametimes for Camera4
Loaded frametimes for Camera5
Loaded frametimes for Camera6


In [2]:
def check_max_shapes_consistency(frametimes_data):
    max_shapes = {camera: data.shape[1] for camera, data in frametimes_data.items()}
    print("Maximum shapes for each camera:", max_shapes)
    
    # Get the set of unique shape values
    unique_shapes = set(max_shapes.values())
    
    # Check if all cameras have the same shape
    return len(unique_shapes) == 1

# Example usage:
result = check_max_shapes_consistency(frametimes_data)
print("All cameras have the same shape:", result)


Maximum shapes for each camera: {'Camera1': 27900, 'Camera2': 27900, 'Camera3': 15748, 'Camera4': 27900, 'Camera5': 27900, 'Camera6': 27900}
All cameras have the same shape: False


In [3]:
import numpy as np

def clone_frame_numbers(frametimes_data):
    cloned_frame_numbers = {}
    for camera, data in frametimes_data.items():
        # Clone the frame numbers (data[0]) for each camera
        cloned_frame_numbers[camera] = np.copy(data[0])
    return cloned_frame_numbers

# Usage
cloned_frame_numbers = clone_frame_numbers(frametimes_data)


In [11]:
frametimes_data

{'Camera1': array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, ...,
         2.78980000e+04, 2.78990000e+04, 2.79000000e+04],
        [0.00000000e+00, 3.33506080e-02, 6.66986720e-02, ...,
         9.30371212e+02, 9.30404560e+02, 9.30437911e+02]]),
 'Camera2': array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, ...,
         2.78980000e+04, 2.78990000e+04, 2.79000000e+04],
        [0.00000000e+00, 3.33473680e-02, 6.66985600e-02, ...,
         9.30369457e+02, 9.30402808e+02, 9.30436159e+02]]),
 'Camera3': array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, ...,
         1.57460000e+04, 1.57470000e+04, 1.57480000e+04],
        [0.00000000e+00, 3.33434480e-02, 6.66946720e-02, ...,
         5.41338787e+02, 5.41538886e+02, 5.41705645e+02]]),
 'Camera4': array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, ...,
         2.78980000e+04, 2.78990000e+04, 2.79000000e+04],
        [0.00000000e+00, 3.33511680e-02, 6.66946960e-02, ...,
         9.30369634e+02, 9.30402981e+02, 9.30436

In [16]:
# Access frame numbers and timestamps for Camera1
camera1_frame_numbers = frametimes_data['Camera1'][0]  # Frame numbers
camera1_timestamps = frametimes_data['Camera1'][1]     # Timestamps

print("Camera1 - Frame Numbers:\n", camera1_frame_numbers)
print("Camera1 - Timestamps:\n", camera1_timestamps)


Camera1 - Frame Numbers:
 [1.0000e+00 2.0000e+00 3.0000e+00 ... 2.7898e+04 2.7899e+04 2.7900e+04]
Camera1 - Timestamps:
 [0.00000000e+00 3.33506080e-02 6.66986720e-02 ... 9.30371212e+02
 9.30404560e+02 9.30437911e+02]


In [17]:
frametimes_data['Camera1'][0][3]

4.0

In [21]:
frametimes_data['Camera1'][1][-1]

930.4379109120001

In [40]:
end_times = {camera: frametimes_data[camera][1][-1] for camera in frametimes_data.keys()}
max_frame_numbers = {camera: frametimes_data[camera][0][-1] for camera in frametimes_data.keys()}


In [23]:
end_times

{'Camera1': 930.4379109120001,
 'Camera2': 930.436158824,
 'Camera3': 541.7056454640001,
 'Camera4': 930.436328672,
 'Camera5': 930.4349932160001,
 'Camera6': 930.436672144}

In [45]:
# max_end_time = max(end_times.values())
# max_end_time = round(max(end_times.values()), 3)  # Round to 3 decimal places, for example
max_end_time = int(round(max(end_times.values())))
max_frame_number = max(max_frame_numbers.values())



In [46]:
max_end_time

930

In [44]:
max_frame_number

27900.0

In [50]:
import numpy as np

frame_interval = 1 / 30  # Interval between frames at 30 fps
standard_timeline = np.arange(0, max_end_time, frame_interval)
standard_frame_numbers = np.arange(0, max_frame_number + 1)


In [48]:
standard_timeline

array([0.00000000e+00, 3.33333333e-02, 6.66666667e-02, ...,
       9.29900000e+02, 9.29933333e+02, 9.29966667e+02])

In [53]:
standard_frame_numbers

array([0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 2.7898e+04, 2.7899e+04,
       2.7900e+04])

In [52]:
standard_frame_numbers[-1]

27900.0