In [1]:
import numpy as np
import scipy.io as sio
import os

In [20]:
def replace_elements(A, B, C):
    # Create a dictionary to map values in A to their indices
    value_to_index = {value: idx for idx, value in enumerate(A)}
    
    # Iterate over the elements in C and replace them with corresponding values from B
    for i in range(len(C)):
        if C[i] in value_to_index:
            index_in_A = value_to_index[C[i]]
            C[i] = B[index_in_A]
    
    return C

# Example arrays
A = [10, 20, 30, 40, 50]
B = [100, 200, 300, 400, 500]
C = [20, 50, 10]

# Replace elements in C
result = replace_elements(A, B, C)
print(result)  # Output should be [200, 500, 100]


[200, 500, 100]


In [22]:
import numpy as np

def replace_elements(A, B, C):
    #replace element of array in C, from A to B. but this method would not handle any nan values in the label....
    # Flatten the input array C to make indexing straightforward
    C_flat = C.flatten()
    
    # Create a dictionary to map values in A to their indices
    value_to_index = {value: idx for idx, value in enumerate(A)}
    
    # Iterate over the flattened array and replace values
    for i in range(len(C_flat)):
        if C_flat[i] in value_to_index:
            index_in_A = value_to_index[C_flat[i]]
            C_flat[i] = B[index_in_A]
    
    # Reshape the flattened array back to the original shape of C
    C = C_flat.reshape(C.shape)
    
    return C

# Example arrays for 1D case
A_1d = [10, 20, 30, 40, 50]
B_1d = [100, 200, 300, 400, 500]
C_1d = np.array([20, 50, 10])

# Replace elements in 1D array
result_1d = replace_elements(A_1d, B_1d, C_1d)
print(result_1d)  # Output should be [200, 500, 100]

# Example arrays for 2D case
A_2d = [1, 2, 3, 4]
B_2d = [10, 20, 30, 40]
C_2d = np.array([[1], [2], [3], [4]], dtype=np.uint8)

# Replace elements in 2D array
result_2d = replace_elements(A_2d, B_2d, C_2d)
print(result_2d)  # Output should be [[10], [20], [30], [40]]


[200 500 100]
[[10]
 [20]
 [30]
 [40]]


In [2]:
old_calib_path = '/home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/calib_convert_test/pos_synced_30s_label3d_dannce.mat'
new_calib_path = '/home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/calib_convert_test/converted_label3d_dannce.mat'

old_calib_data = sio.loadmat(old_calib_path)
new_calib_data = sio.loadmat(new_calib_path)

In [3]:
label_path = '/home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/mir_sampleid_4framelabel_test_20240802_173848_Label3D_dannce.mat'
label_data = sio.loadmat(label_path)

In [5]:
# step one: replace sync:
label_data['sync'] = new_calib_data['sync']

In [10]:
dff = 'data_frame'
sid = 'data_sampleID'
labels = label_data['labelData']

In [18]:
new_sync = new_calib_data['sync']
old_sync = old_calib_data['sync']

In [17]:
new_sync[0][0][dff][0][0][0]

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 18

In [19]:
old_sync[0][0][dff][0][0][0]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [31]:
old_sync[0][0][sid][0][0][0]

array([ nan,  nan,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,
         9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,
        20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
        31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,
        42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,
        53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,
        64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,
        75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,
        86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
        97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107.,
       108., 109., 110., 111., 112., 113., 114., 115., 116., 117., 118.,
       119., 120., 121., 122., 123., 124., 125., 126., 127., 128., 129.,
       130., 131., 132., 133., 134., 135., 136., 137., 138., 139., 140.,
       141., 142., 143., 144., 145., 146., 147., 14

In [32]:
new_sync[0][0][sid][0][0][0]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [26]:
labels[0][0][dff][0][0]

array([[1],
       [2],
       [3],
       [4]], dtype=uint8)

In [25]:
labels[0][0][sid][0][0]

array([[nan, nan,  0.,  1.]])

In [33]:
# then convert all incidences in the data 
label_dff = labels[0][0][dff][0][0]
label_sid = labels[0][0][sid][0][0]

old_sync_dff = old_sync[0][0][dff][0][0][0]
old_sync_sid = old_sync[0][0][sid][0][0][0]

new_sync_dff = new_sync[0][0][dff][0][0][0]
new_sync_sid = new_sync[0][0][sid][0][0][0]

new_label_dff = replace_elements(old_sync_dff, new_sync_dff, label_dff)
new_label_sid = replace_elements(old_sync_sid, new_sync_sid, label_sid)

    

In [28]:
new_label_dff

array([[3],
       [4],
       [5],
       [6]], dtype=uint8)

In [34]:
new_label_sid

array([[nan, nan,  3.,  4.]])

In [30]:
new_sync_sid

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [38]:
# not try to sort out working tree...
import numpy as np

def replace_elements(A, B, C):
    #replace element of array in C, from A to B. but this method would not handle any nan values in the label....
    # Flatten the input array C to make indexing straightforward
    C_flat = C.flatten()
    
    # Create a dictionary to map values in A to their indices
    value_to_index = {value: idx for idx, value in enumerate(A)}
    
    # Iterate over the flattened array and replace values
    for i in range(len(C_flat)):
        if C_flat[i] in value_to_index:
            index_in_A = value_to_index[C_flat[i]]
            C_flat[i] = B[index_in_A]
    
    # Reshape the flattened array back to the original shape of C
    C = C_flat.reshape(C.shape)
    
    return C

def count_leading_nans(arr):
    count = 0
    for val in arr:
        if np.isnan(val):
            count += 1
        else:
            break
    return count

In [46]:
old_calib_path = '/home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/calib_convert_test/pos_synced_30s_label3d_dannce.mat'
new_calib_path = '/home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/calib_convert_test/converted_label3d_dannce.mat'
label_path = '/home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/mir_sampleid_4framelabel_test_20240802_173848_Label3D_dannce.mat'
new_label_name = '2_reverted_label_Label3D_dannce.mat'

old_calib_data = sio.loadmat(old_calib_path)
new_calib_data = sio.loadmat(new_calib_path)
label_data = sio.loadmat(label_path)

dff = 'data_frame'
sid = 'data_sampleID'

labels = label_data['labelData']
new_sync = new_calib_data['sync']
old_sync = old_calib_data['sync']

for camera_idx in range(6):
    old_sync_sid = old_sync[camera_idx][0][sid][0][0][0]

    if old_sync_sid[0]==0:
        good_label_sid = labels[camera_idx][0][sid][0][0]
        valid_label_sid = [x + 1 for x in good_label_sid]

for camera_idx in range(6):
    old_sync_sid = old_sync[camera_idx][0][sid][0][0][0]
    new_label_sid = valid_label_sid
    
    if old_sync_sid[0]==0:
        labels[camera_idx][0][sid][0][0] = new_label_sid
        continue
    # then convert all incidences in the data 
    label_dff = labels[camera_idx][0][dff][0][0]
    # label_sid = labels[camera_idx][0][sid][0][0]

    old_sync_dff = old_sync[camera_idx][0][dff][0][0][0]
    

    new_sync_dff = new_sync[camera_idx][0][dff][0][0][0]
    # new_sync_sid = new_sync[camera_idx][0][sid][0][0][0]

    new_label_dff = replace_elements(old_sync_dff, new_sync_dff, label_dff)
    # replace_elements(old_sync_sid, new_sync_sid, label_sid)

    labels[camera_idx][0][dff][0][0] = new_label_dff
    labels[camera_idx][0][sid][0][0] = new_label_sid




# step one: replace sync:
label_data['sync'] = new_calib_data['sync']
label_data['labelData'] = labels


base_path = os.path.dirname(label_path)
save_path = os.path.join(base_path, new_label_name)

sio.savemat(save_path, label_data)
print('converted label data saved to:', save_path) 

converted label data saved to: /home/lq53/mir_data/sync_test/rawvid_mirstop_30s_light_3/timdataframe_sampleid_rescue/2_reverted_label_Label3D_dannce.mat
