In [3]:
import scipy.io as sio
import numpy as np
from projection import load_cameras

def compare_params(dict1, dict2):
    # Load the camera parameters from the two .mat files
    param1 = load_cameras(dict1)
    param2 = load_cameras(dict2)
    
    # Get the common cameras from both sets (assuming the same camera names are present)
    common_cameras = set(param1.keys()).intersection(set(param2.keys()))
    
    for cam in common_cameras:
        print(f"\nComparing camera: {cam}")

        # List of parameters to compare
        params_to_compare = ["K", "r", "t", "RDistort", "TDistort"]
        
        for param in params_to_compare:
            # Extract and compare each parameter
            param_val1 = np.squeeze(param1[cam][param])
            param_val2 = np.squeeze(param2[cam][param])

            # Check if the values are different
            if not np.allclose(param_val1, param_val2):
                print(f"  Difference in {param}:")
                print(f"    File 1 value:\n{param_val1}")
                print(f"    File 2 value:\n{param_val2}")
            else:
                print(f"  {param} is identical between the files.")





dir1 = '/home/lq53/mir_data/chris_new_method_test/chris_new_label3d_dannce.mat'
# dir2 = '/home/lq53/mir_data/chris_new_method_test/chrris_prev_label3d_dannce.mat' prev before update
dir2 = '/home/lq53/mir_data/chris_new_method_test/updated/chrris_prev_label3d_dannce.mat'

compare_params(dir1, dir2)


Comparing camera: Camera5
  Difference in K:
    File 1 value:
[[1.74969978e+03 0.00000000e+00 1.14419817e+03]
 [0.00000000e+00 1.74851896e+03 9.10519728e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
    File 2 value:
[[1.74969978e+03 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.74851896e+03 0.00000000e+00]
 [1.14319817e+03 9.09519728e+02 1.00000000e+00]]
  Difference in r:
    File 1 value:
[[-0.77052358 -0.63710941  0.01962164]
 [-0.31528593  0.35419338 -0.8804214 ]
 [ 0.5539749  -0.68457187 -0.47378598]]
    File 2 value:
[[-0.63746947  0.35377336 -0.68445386]
 [-0.7702303  -0.31502432  0.5545313 ]
 [-0.01944121  0.88068387  0.47330535]]
  Difference in t:
    File 1 value:
[ -62.59675868 -196.11749751 1289.04783431]
    File 2 value:
[ -61.85146883 -195.36318516 1288.94371271]
  RDistort is identical between the files.
  TDistort is identical between the files.

Comparing camera: Camera6
  Difference in K:
    File 1 value:
[[1.77978328e+03 0.00000000e+00 1.16330185e+